Potrzebuję pomocy wyskakuje błąd
SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_TestPublications_Tests_TestId". The conflict occurred in database "EgzaminerDb", table "dbo.Tests", column 'Id'.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_AnswerSubmitted_Questions_QuestionId". The conflict occurred in database "EgzaminerDb", table "dbo.Questions", column 'Id'.
The statement has been terminated.
The statement has been terminated.